/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpu.schedulers.simulator;

import java.awt.Color;
import java.awt.Insets;
import java.awt.Point;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

public class Graphical_representation extends javax.swing.JFrame {
    
    globalInput obj = new globalInput();
    NP_SJF tech1 = new NP_SJF(obj.in);
    SRTF tech2 = new SRTF(obj.in);
    PriorityScheduling tech3 = new PriorityScheduling(obj.in);
    AG tech4 = new AG(obj.in);
    boolean Run = false;
    /*
    Input in = new Input();
    NP_SJF tech1 = new NP_SJF(in);
    SRTF tech2 = new SRTF(in);
    PriorityScheduling tech3 = new PriorityScheduling(in);
    AG tech4 = new AG(in);
    */
    DefaultTableModel model;
    /**
     * Creates new form Graphical_representation
     */
    public Graphical_representation() {
        initComponents();
        model = (DefaultTableModel) tblData.getModel();
        panelHistory.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        run = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        NP_SJF = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        SRTF = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        NP_PS = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        AG = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        ATAT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AWT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panelHistory = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textHistory = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graphical representation");
        setAutoRequestFocus(false);

        jPanel2.setBackground(new java.awt.Color(50, 53, 55));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Process Information");

        tblData.setAutoCreateRowSorter(true);
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Process", "Color", "Name", "PID", "Priority"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(tblData);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ATAT :");

        run.setText("RUN");
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout NP_SJFLayout = new javax.swing.GroupLayout(NP_SJF);
        NP_SJF.setLayout(NP_SJFLayout);
        NP_SJFLayout.setHorizontalGroup(
            NP_SJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NP_SJFLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1047, Short.MAX_VALUE))
        );
        NP_SJFLayout.setVerticalGroup(
            NP_SJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(NP_SJF);

        jTabbedPane1.addTab("NP_SJF", jScrollPane2);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout SRTFLayout = new javax.swing.GroupLayout(SRTF);
        SRTF.setLayout(SRTFLayout);
        SRTFLayout.setHorizontalGroup(
            SRTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SRTFLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1047, Short.MAX_VALUE))
        );
        SRTFLayout.setVerticalGroup(
            SRTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(SRTF);

        jTabbedPane1.addTab("SRTF", jScrollPane3);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout NP_PSLayout = new javax.swing.GroupLayout(NP_PS);
        NP_PS.setLayout(NP_PSLayout);
        NP_PSLayout.setHorizontalGroup(
            NP_PSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NP_PSLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1047, Short.MAX_VALUE))
        );
        NP_PSLayout.setVerticalGroup(
            NP_PSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NP_PS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NP_PS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("NP_PS", jScrollPane1);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout AGLayout = new javax.swing.GroupLayout(AG);
        AG.setLayout(AGLayout);
        AGLayout.setHorizontalGroup(
            AGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1047, Short.MAX_VALUE))
        );
        AGLayout.setVerticalGroup(
            AGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jScrollPane4.setViewportView(jPanel4);

        jTabbedPane1.addTab("AG", jScrollPane4);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("CPU Scheduling Graph");

        ATAT.setEditable(false);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AWT  :");

        AWT.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Statistics");

        textHistory.setColumns(20);
        textHistory.setRows(5);
        jScrollPane6.setViewportView(textHistory);

        jLabel6.setText("Quantum history");

        javax.swing.GroupLayout panelHistoryLayout = new javax.swing.GroupLayout(panelHistory);
        panelHistory.setLayout(panelHistoryLayout);
        panelHistoryLayout.setHorizontalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(170, 170, 170))
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelHistoryLayout.setVerticalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistoryLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AWT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ATAT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(ATAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(AWT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(panelHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void seperat(JPanel pane,int i){
        JSeparator sep = new JSeparator(SwingConstants.VERTICAL);
        sep.setBounds(60+i*20, 0, 1, obj.in.numberOfProcesses * 50);
        if      (i%5 == 0)sep.setForeground(Color.BLACK);
        else    sep.setForeground(new Color(128,128,128));
        pane.add(sep);
    }
    
    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        // TODO add your handling code here:
        int end = Math.max(Math.max(Math.max(tech1.processes.get(tech1.processes.size()-1).endTime ,tech2.lastend ),tech3.save.get(tech3.save.size()-1).CT ),tech4.outPut.get(tech4.outPut.size()-1).BT );
        for(int i=0 ; i<end+2+obj.in.arrivalTimes.get(0) ;++i){
            seperat(NP_SJF, i);
            seperat(SRTF, i);
            seperat(NP_PS, i);
            seperat(AG, i);
        }
        tech1.processes.sort(Comparator.comparing(save->save.name));
        tech3.save.sort(Comparator.comparing(save->save.name));
        tech4.outPut.sort(Comparator.comparing(save->save.name));
        Run = true;
        panelHistory.setVisible(false);
        model.setRowCount(0);
        /*Technique 1*/
        JLabel labName;
        int pos = 50;
        JLabel labIcon;
        for(int i=0 ; i<tech1.processes.size() ; ++i){
            labName = new JLabel();
            labIcon = new JLabel();
            labName.setText(tech1.processes.get(i).name);
            NP_SJF.add(labName);
            labName.setBounds(new Rectangle(new Point(10,i*pos+10) , labName.getPreferredSize()));
            
            labIcon.setIcon(new ImageIcon("D:\\Education\\Java\\CPU-Schedulers-Simulator\\colors" + "\\"+ tech1.processes.get(i).color + ".jpg"));
            NP_SJF.add(labIcon);
            labIcon.setBounds(new Rectangle(new Point(60 + tech1.processes.get(i).beginTime *20 ,i*pos+10) , labIcon.getPreferredSize()));
            labIcon.setSize( tech1.processes.get(i).burstTime*20 ,15);
        }
        
        /*Table*/
        int PID = 3280;
        for (int i=0 ; i < obj.in.numberOfProcesses ; i++){
            model.insertRow(tblData.getRowCount(), new Object[]{i+1,obj.in.colors.get(i),obj.in.names.get(i)
                            ,PID+i,obj.in.priorityNumbers.get(i)});
        }
        /*AWT*/
        AWT.setText(String.format( "%.3f", tech1.averageWaitingTime));
        /*ATAT*/
        ATAT.setText(String.format( "%.3f",  tech1.averageTurnaroundTime));
    }//GEN-LAST:event_runActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        int sel = jTabbedPane1.getSelectedIndex();
        if(sel == 0 && Run){                       /*Technique 1*/
            panelHistory.setVisible(false);
            /*AWT*/
            AWT.setText(String.format( "%.3f", tech1.averageWaitingTime));
            /*ATAT*/
            ATAT.setText(String.format( "%.3f",  tech1.averageTurnaroundTime));
        }
        else if(sel == 1 && Run)                   /*Technique 2*/
        {
            panelHistory.setVisible(false);
            JLabel labName;
            JLabel labIcon;
            int pos = 50;
            int savex = 0;
            boolean check = false;
            for(int i=0 ; i<tech2.processes.size() ; ++i){
                labName = new JLabel();
                labIcon = new JLabel();
                labName.setText(tech2.processes.get(i).name);
                SRTF.add(labName);
                labName.setBounds(new Rectangle(new Point(10,savex*pos+10) , labName.getPreferredSize()));
                if(i != tech2.processes.size()-1){
                    labIcon = new JLabel();
                    labIcon.setIcon(new ImageIcon("D:\\Education\\Java\\CPU-Schedulers-Simulator\\colors" + "\\"+ tech2.processes.get(i).color + ".jpg"));
                    SRTF.add(labIcon);
                    labIcon.setBounds(new Rectangle(new Point(60 + tech2.processes.get(i).BT *20 , savex*pos +10 ) , labIcon.getPreferredSize()));
                    labIcon.setSize((tech2.processes.get(i).ET - tech2.processes.get(i).BT) *20 ,15);
                    while(tech2.processes.get(i).name.matches(tech2.processes.get(i+1).name)){
                        check = true;
                        i++;
                        labIcon = new JLabel();
                        labIcon.setIcon(new ImageIcon("D:\\Education\\Java\\CPU-Schedulers-Simulator\\colors" + "\\"+ tech2.processes.get(i).color + ".jpg"));
                        SRTF.add(labIcon);
                        labIcon.setBounds(new Rectangle(new Point(60 + tech2.processes.get(i).BT *20 , savex*pos +10) , labIcon.getPreferredSize()));
                        labIcon.setSize((tech2.processes.get(i).ET - tech2.processes.get(i).BT) *20 ,15);
                        if(i == tech2.processes.size()-1) break;
                    }
                    savex++;
                }
                else
                {
                    labIcon = new JLabel();
                    labIcon.setIcon(new ImageIcon("D:\\Education\\Java\\CPU-Schedulers-Simulator\\colors" + "\\"+ tech2.processes.get(i).color + ".jpg"));
                    SRTF.add(labIcon);
                    labIcon.setBounds(new Rectangle(new Point(60 + tech2.processes.get(i).BT *20 , savex*pos +10 ) , labIcon.getPreferredSize()));
                    labIcon.setSize((tech2.processes.get(i).ET - tech2.processes.get(i).BT) *20 ,15);
                }
            }
            /*AWT*/
            AWT.setText(String.format( "%.3f", tech2.AWT));
            /*ATAT*/
            ATAT.setText(String.format( "%.3f", tech2.ATAT));
        }
        else if(sel == 2 && Run)  {                    /*Technique 3*/
            panelHistory.setVisible(false);
            JLabel labName;
            int pos = 50;
            int shift = 0;
            JLabel labIcon;
            for(int i=0 ; i<tech3.save.size() ; ++i){
                labName = new JLabel();
                labIcon = new JLabel();
                labName.setText(tech3.save.get(i).name);
                NP_PS.add(labName);
                labName.setBounds(new Rectangle(new Point(10,i*pos+10) , labName.getPreferredSize()));

                labIcon.setIcon(new ImageIcon("D:\\Education\\Java\\CPU-Schedulers-Simulator\\colors" + "\\"+ tech3.save.get(i).color + ".jpg"));
                NP_PS.add(labIcon);
                labIcon.setBounds(new Rectangle(new Point(60 + tech3.save.get(i).ST*20 ,i*pos+10) , labIcon.getPreferredSize()));
                labIcon.setSize( (tech3.save.get(i).CT - tech3.save.get(i).ST)*20 ,15);
                shift += (tech3.save.get(i).CT - tech3.save.get(i).ST)*20;
            }
            /*AWT*/
            AWT.setText(String.format( "%.3f", tech3.AvgWT));
            /*ATAT*/
            ATAT.setText(String.format( "%.3f", tech3.AvgTAT));
        }
        else if(sel == 3 && Run){                                   /*Technique 4*/
            panelHistory.setVisible(true);
            JLabel labName;
            JLabel labIcon;
            int pos = 50;
            int savex = 0;
            boolean check = false;
            for(int i=0 ; i<tech4.outPut.size() ; ++i){
                labName = new JLabel();
                labIcon = new JLabel();
                labName.setText(tech4.outPut.get(i).name);
                AG.add(labName);
                labName.setBounds(new Rectangle(new Point(10,savex*pos+10) , labName.getPreferredSize()));
                if(i != tech4.outPut.size()-1){
                    labIcon = new JLabel();
                    labIcon.setIcon(new ImageIcon("D:\\Education\\Java\\CPU-Schedulers-Simulator\\colors" + "\\"+ tech4.outPut.get(i).color + ".jpg"));
                    AG.add(labIcon);
                    labIcon.setBounds(new Rectangle(new Point(60 + tech4.outPut.get(i).AT *20 , savex*pos +10 ) , labIcon.getPreferredSize()));
                    labIcon.setSize((tech4.outPut.get(i).BT - tech4.outPut.get(i).AT) *20 ,15);
                    while(tech4.outPut.get(i).name.matches(tech4.outPut.get(i+1).name)){
                        check = true;
                        i++;
                        labIcon = new JLabel();
                        labIcon.setIcon(new ImageIcon("D:\\Education\\Java\\CPU-Schedulers-Simulator\\colors" + "\\"+ tech4.outPut.get(i).color + ".jpg"));
                        AG.add(labIcon);
                        labIcon.setBounds(new Rectangle(new Point(60 + tech4.outPut.get(i).AT *20 , savex*pos +10) , labIcon.getPreferredSize()));
                        labIcon.setSize((tech4.outPut.get(i).BT - tech4.outPut.get(i).AT) *20 ,15);
                        if(i == tech4.outPut.size()-1) break;
                    }
                    savex++;
                }
                else
                {
                    labIcon = new JLabel();
                    labIcon.setIcon(new ImageIcon("D:\\Education\\Java\\CPU-Schedulers-Simulator\\colors" + "\\"+ tech4.outPut.get(i).color + ".jpg"));
                    AG.add(labIcon);
                    labIcon.setBounds(new Rectangle(new Point(60 + tech4.outPut.get(i).AT *20 , savex*pos +10 ) , labIcon.getPreferredSize()));
                    labIcon.setSize((tech4.outPut.get(i).BT - tech4.outPut.get(i).AT) *20 ,15);
                }
            }
            /*Quantum history*/
            if(tech4.quantumHistory.size() == 0){
                textHistory.setText("No History");
            }
            for (int i=0; i<tech4.quantumHistory.size(); i++){
                textHistory.setText(textHistory.getText()+(tech4.quantumHistory.get(i).name +" "+tech4.quantumHistory.get(i).quantumTime)+"\n");
            }
            /*AWT*/
            AWT.setText(String.format( "%.3f", tech4.getAwt()));
            /*ATAT*/
            ATAT.setText(String.format( "%.3f", tech4.getATAT()));
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphical_representation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphical_representation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphical_representation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphical_representation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graphical_representation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AG;
    private javax.swing.JTextField ATAT;
    private javax.swing.JTextField AWT;
    private javax.swing.JPanel NP_PS;
    private javax.swing.JPanel NP_SJF;
    private javax.swing.JPanel SRTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelHistory;
    private javax.swing.JButton run;
    private javax.swing.JTable tblData;
    private javax.swing.JTextArea textHistory;
    // End of variables declaration//GEN-END:variables
}
